spring:
  datasource:
    url : jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:employee}
    username : ${DB_USER:root}
    password : ${DB_PWD:root}

  jpa:
    hibernate:
      ddl-auto : update
      dialect:  org.hibernate.dialect.PostgreSQLDialect
      naming_strategy : org.hibernate.cfg.ImprovedNamingStrategy